name: 'Test'

on:
  [push, pull_request, workflow_dispatch]

jobs:
  style-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install Poetry
      run: pip install poetry

    - name: Install project dependencies
      run: poetry update -vvv

    - name: Check style with black
      run: poetry run poe run_black_check

    - name: Check style with isort
      run: poetry run poe run_isort_check

  stub-tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10']
    needs: style-check

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install Poetry
      run: pip install poetry

    - name: Install project dependencies
      run: poetry update -vvv

    - name: Run MyPy Against Source Code
      run: poetry run poe run_mypy_src

    - name: Run Pyright Against Source Code
      run: poetry run poe run_pyright_src

    - name: Run Pytest Against Source Code
      run: poetry run poe run_pytest_src

    - name: Build Distribution
      run: poetry run poe build_dist

    - name: Install Distribution
      run: poetry run poe install_dist

    - name: Remove Source Code
      run: poetry run poe remove_src

    - name: Run Pyright Against Distribution
      run: poetry run poe run_pyright_dist

    - name: Run MyPy Against Distribution
      run: poetry run poe run_mypy_dist